function showMenu() {
	var menuTxt = '';
	menuTxt += '<ul class="menu">';
	menuTxt += '<li class="menu"><a href="#">Master Data</a>';
	menuTxt += '<ul class="menu"> ';
	menuTxt += '<li class="menu"><a href="../employee/EmployeeList.html">Employee</a></li>';
	menuTxt += '<li class="menu"><a href="#">Role</a></li>';
	menuTxt += '<li class="menu"><a href="../orgStructure/OrgStructure.html">Org Structure</a></li>';
	menuTxt += '<li class="menu"><a href="../compRule/CompRule.html">Comp Rule</a></li>';
	menuTxt += '<li class="menu"><a href="#">Credit Rollup Rule</a></li>';
	menuTxt += '</ul> ';
	menuTxt += '</li>';
	menuTxt += '<li class="menu"><a href="#">Booking</a>';
	menuTxt += '<ul class="menu"> ';
	menuTxt += '<li class="menu"><a href="#">Orders / Booking</a></li>';
	menuTxt += '</ul> ';
	menuTxt += '</li>';
	menuTxt += '<li class="menu"><a href="#">Comp Plan</a>';
	menuTxt += '<ul class="menu"> ';
	menuTxt += '<li class="menu"><a href="#">Employee Comp Plan</a></li>';
	menuTxt += '<li class="menu"><a href="#">Role Comp Plan</a></li>';
	menuTxt += '</ul> ';
	menuTxt += '</li>';
	menuTxt += '<li class="menu"><a href="#">Compensation</a>';
	menuTxt += '<ul class="menu"> ';
	menuTxt += '<li class="menu"><a href="#">Employee Comp Report</a></li>';
	menuTxt += '</ul> ';
	menuTxt += '</li>';
	menuTxt += '</ul>';
	$("#menu").html(menuTxt);
	$("#buffer").html('&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>&nbsp;<br>');
}
